### ISSUE TITLE
Make CBGT UI more "embeddable"

### ISSUE THREAD

**Issue by tleyden** [couchbase/cbgt#4]
- Use relative paths in the static assets
- Somehow pass a prefix to the javascript code

See https://github.com/couchbase/sync_gateway/issues/1152

**Comment by steveyen** [comment]
Just ran into this for other reasons and realizing this might be part of the solution, so leaving this here...

```
https://docs.angularjs.org/error/$location/nobase
```

**Comment by steveyen** [comment]
Some commits that make this possible for an app to have its own URL prefix (but not necessarily easy to use)...

  https://github.com/couchbase/cbgt/commit/3370bf0dd0f84c40d9ea50b020f0abc9592cc033

  https://github.com/couchbase/cbgt/commit/be9dc5b8ff00711a67e47d0418f771e48f2a1167
